name: PR description checker
description: Checks if PR description is present, in case of templated description it checks whether it is filled in or not
inputs:
  repo-token:
    description: The GITHUB_TOKEN secret
    required: true
  exempt-labels:
    description: PR labels that should be skipped, comma separated
    default: ""
  template-path:
    description: Path to PR template if custom
    default: "./.github/PULL_REQUEST_TEMPLATE.md"
  comment:
    description: Whether to add comment to PR
    default: true
  comment-empty-description:
    description: Comment to use when empty description
    default: PR description is empty, please add some valid description
  comment-template-not-filled:
    description: Comment to use when template not filled in
    default: PR description is too short and seems to not fulfill PR template, please fill in
  comment-github-token:
    description: Github token to use while creating comment
    default: ""

runs:
  using: composite
  steps:
    - shell: bash
      id: determine-arch
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          echo "ARCH=amd64" >> $GITHUB_OUTPUT
        elif [[ "$(uname -m)" == "aarch64" ]]; then
          echo "ARCH=arm64" >> $GITHUB_OUTPUT
        else
          echo "Unsupported architecture"
          exit 1
        fi

    - shell: bash
      run: $GITHUB_ACTION_PATH/bin/description-checker-${{ steps.determine-arch.outputs.ARCH }}
      env:
        INPUT_PR-NUMBER: ${{ github.event.number }}
        INPUT_REPO-OWNER: ${{ github.event.repository.owner.login }}
        INPUT_REPO-NAME: ${{ github.event.repository.name }}
        INPUT_REPO-TOKEN: ${{ inputs.repo-token }}
        INPUT_EXEMPT-LABELS: ${{ inputs.exempt-labels }}
        INPUT_TEMPLATE-PATH: ${{ inputs.template-path }}
        INPUT_COMMENT: ${{ inputs.comment }}
        INPUT_COMMENT-EMPTY-DESCRIPTION: ${{ inputs.comment-empty-description }}
        INPUT_COMMENT-TEMPLATE-NOT-FILLED: ${{ inputs.comment-template-not-filled }}
        INPUT_COMMENT-GITHUB-TOKEN: ${{ inputs.comment-github-token }}
